# 공통 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver    # MariaDB 드라이버 클래스 이름 설정

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    hibernate:
      ddl-auto: create    # 실행시 DB 초기화 후 DDL 실행
    properties:
      hibernate:
        format_sql: true    # SQL 쿼리 보기 좋게 표시
        show_sql: true    # SQL 쿼리 확인
#        hbm2ddl:
#          connection:
#            charSet: UTF-8 # 인코딩 설정

  datasource:
    url: jdbc:mariadb://localhost:3306/s09p12c210    # 데이터베이스 URL 설정
    username: ${DB_ID}    # DB 사용자 이름 설정
    password: ${DB_PW}    # DB 사용자 암호 설정
  sql:
    init:
      encoding: UTF-8

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    hibernate:
      ddl-auto: none    # 실행시 DB 그대로
    properties:
      hibernate:
        format_sql: false    # SQL 쿼리 보기 좋게 표시 X
        show_sql: false    # SQL 쿼리 확인 X
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12C210
    username: ${DB_ID}
    password: ${DB_PW}