# 공통 설정
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
              - nickname
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

--- # local 설정
spring:
  config:
    activate:
      on-profile: "oauth2-local"
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/api/oauth2/callback/naver
app:
  oauth2:
    authorized-redirect-uris: http://localhost:3000/redirect


--- # dev 설정
spring:
  config:
    activate:
      on-profile: "oauth2-dev"
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://i9c210.p.ssafy.io/api/oauth2/callback/naver
app:
  oauth2:
    authorized-redirect-uris: https://i9c210.p.ssafy.io/redirect